x-airflow-common: &airflow-common
  image: apache/airflow:3.1.7
  env_file:
    - .env
  environment:
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    AIRFLOW__CORE__TEST_CONNECTION: "Enabled"
    AIRFLOW__CORE__EXECUTION_API_SERVER_URL: "http://airflow-apiserver:8080/execution/"
    AIRFLOW__API_AUTH__JWT_SECRET: "insurance-dw-secret-2026"
    AIRFLOW__CORE__FERNET_KEY: "nKZbIM7yCDoLKXvQeMhJSwIwNUryOMleD9150NXvFPc="
  volumes:
    - ./dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
    - ./plugins:/opt/airflow/plugins
    - ./config:/opt/airflow/config
    - ./sql:/opt/airflow/sql
    - ./config/simple_auth_manager_passwords.json:/opt/airflow/simple_auth_manager_passwords.json.generated
  depends_on:
    postgres:
      condition: service_healthy

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "airflow" ]
      interval: 10s
      retries: 5

  airflow-init:
    <<: *airflow-common
    command: >
      bash -c "airflow db migrate"
    restart: "no"

  airflow-apiserver:
    <<: *airflow-common
    command: api-server
    ports:
      - "8080:8080"
    restart: always

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler
    restart: always

  airflow-dag-processor:
    <<: *airflow-common
    command: dag-processor
    restart: always

  airflow-triggerer:
    <<: *airflow-common
    command: triggerer
    restart: always

volumes:
  postgres-db-volume:
